#!/usr/bin/python3
conf_read = open('/etc/wireguard/wg0.conf', 'r')
conf = conf_read.readlines()
conf_read.close()

ips = set()

for line in conf:
  if 'AllowedIPs' in line:
    ips.add(line.split('=')[-1].strip())

ips_list = sorted(list(map(lambda x: x.split('/')[0], ips)))
ips_list.sort(key=lambda x: int(x.split('.')[-1]))

# increment last ip
new_ip = '10.0.0.2'.split('.')
if len(ips_list) > 0:
  last_ip = ips_list[-1].split('.')
  new_ip = last_ip[:3] + [str(int(last_ip[-1]) + 1)]
print('.'.join(new_ip))
